In [3]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

In [5]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

In [7]:
arr = np.array(my_list)  # list to array

In [8]:
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr) # N-Dimensional Array

numpy.ndarray

In [10]:
type(my_list)

list

In [11]:
np.arange(5) # Create array from list..

array([0, 1, 2, 3, 4])

In [12]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [13]:
np.arange(0,7)

array([0, 1, 2, 3, 4, 5, 6])

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(20,10) # 1st arg always be less then 2nd arg

array([], dtype=int32)

In [16]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(-25,9)

array([-25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,
         1,   2,   3,   4,   5,   6,   7,   8])

In [18]:
b = np.arange(-15,10)

In [19]:
b

array([-15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,
        -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [20]:
np.arange(10,30,3) #  # 10- starting from 30- end point 3 - step count

array([10, 13, 16, 19, 22, 25, 28])

In [21]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.arange(0,20,2,2) # 4th arg not allowed

TypeError: Cannot interpret '2' as a data type

In [23]:
a1 = np.zeros(3) # Array of all 0s
a1

array([0., 0., 0.])

In [24]:
np.zeros(4) # default dtype is float 

array([0., 0., 0., 0.])

In [25]:
np.zeros(5,dtype=int) #hyperparameter tunning 

array([0, 0, 0, 0, 0])

In [26]:
b1 = np.zeros((2,3)) # 1st arg denots rows & 2nd arg denots column
b1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.zeros((10,10),dtype=int) # 10 rows & 10 cols

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [28]:
np.zeros((10,20),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
np.zeros((3,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [30]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
n = (5,7) # parameter tunnin
(np.zeros(n))  

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [32]:
n1 = (6,8) # hypyerparameter tunning
np.zeros(n1,dtype=int) 

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [33]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [35]:
n

(5, 7)

In [36]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [37]:
np.ones((5,4),dtype=int) #  # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [38]:
from numpy import *  # Everything import from numpy 

In [39]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
range(10)
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [41]:
y = list(range(15))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [42]:
rand(10.20)
random.rand(10,20)

NameError: name 'rand' is not defined

In [43]:
np.random.rand(3,5) # bydefault dtype is float

array([[0.18322938, 0.37758148, 0.0717471 , 0.87799199, 0.61445056],
       [0.17027129, 0.63137177, 0.82427412, 0.48395254, 0.05060745],
       [0.93326682, 0.02124981, 0.22560001, 0.76587015, 0.43838352]])

In [44]:
np.random.rand(5)

array([0.31854477, 0.6164883 , 0.37728562, 0.91334614, 0.85513195])

In [45]:
np.random.rand(2,5)

array([[0.52917981, 0.85381956, 0.05560359, 0.81794854, 0.96835797],
       [0.76595308, 0.83333324, 0.97127041, 0.44180003, 0.66691721]])

In [46]:
np.random.randint(2,20) # 2nd argument is exlusive 

2

In [47]:
np.random.randint(1,10,4) # genarate 4 random no..  1-starting from 10- end points

array([7, 1, 5, 7])

In [48]:
np.random.randint(1,3,5)

array([1, 2, 1, 1, 2])

In [49]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

5

In [50]:
np.random.randint(10,40,(10,10)) # ganarate the element 10 to 30 with 10*10 mtri

array([[31, 23, 37, 19, 12, 39, 33, 31, 36, 11],
       [12, 22, 19, 23, 18, 24, 20, 14, 19, 26],
       [35, 13, 26, 37, 14, 31, 22, 18, 23, 26],
       [13, 34, 27, 13, 36, 24, 32, 15, 10, 34],
       [19, 31, 12, 15, 10, 23, 36, 19, 31, 31],
       [33, 12, 18, 28, 31, 26, 37, 32, 14, 19],
       [28, 29, 27, 20, 15, 18, 36, 31, 31, 20],
       [10, 23, 11, 21, 21, 22, 14, 37, 39, 12],
       [17, 29, 23, 34, 12, 33, 39, 13, 11, 26],
       [27, 27, 22, 38, 11, 19, 21, 13, 35, 24]])

In [51]:
c = np.random.randint(10,20,(5,4))
c

array([[12, 17, 18, 17],
       [10, 16, 14, 19],
       [13, 18, 18, 16],
       [16, 17, 10, 11],
       [10, 18, 12, 13]])

In [52]:
c[:] # colon (:) used for sciling rows

array([[12, 17, 18, 17],
       [10, 16, 14, 19],
       [13, 18, 18, 16],
       [16, 17, 10, 11],
       [10, 18, 12, 13]])

In [53]:
c[0:3,2:]

array([[18, 17],
       [14, 19],
       [18, 16]])

In [54]:
c

array([[12, 17, 18, 17],
       [10, 16, 14, 19],
       [13, 18, 18, 16],
       [16, 17, 10, 11],
       [10, 18, 12, 13]])

In [55]:
c[0:-1]

array([[12, 17, 18, 17],
       [10, 16, 14, 19],
       [13, 18, 18, 16],
       [16, 17, 10, 11]])

In [56]:
c

array([[12, 17, 18, 17],
       [10, 16, 14, 19],
       [13, 18, 18, 16],
       [16, 17, 10, 11],
       [10, 18, 12, 13]])

In [57]:
c[3,3] # comma (,) used for indexing elements

11

In [58]:
c[2,1]

18

In [59]:
c

array([[12, 17, 18, 17],
       [10, 16, 14, 19],
       [13, 18, 18, 16],
       [16, 17, 10, 11],
       [10, 18, 12, 13]])

In [60]:
c[:,2:]

array([[18, 17],
       [14, 19],
       [18, 16],
       [10, 11],
       [12, 13]])

In [61]:
c[:,2:3]

array([[18],
       [14],
       [18],
       [10],
       [12]])

In [62]:
c[0:3,:]

array([[12, 17, 18, 17],
       [10, 16, 14, 19],
       [13, 18, 18, 16]])

In [63]:
arr2 = np.random.randint(0,100,(10,10))

In [65]:
arr2

array([[60, 10, 23, 82,  2, 81, 73, 85, 67, 22],
       [53, 15, 84, 15, 85, 23, 77, 91, 74, 36],
       [75, 29,  7, 99, 93, 19,  3, 72, 72, 80],
       [96, 53, 58, 65, 29,  0, 76, 83, 22, 41],
       [95, 37, 58,  6, 53, 78, 21, 64, 15,  8],
       [11, 81, 15, 20, 16, 22, 95, 19, 94, 98],
       [17, 30, 14, 15,  8, 33, 78, 71, 33, 27],
       [62, 26, 50, 95, 77, 18, 46, 64, 37, 82],
       [79, 64, 49, 14, 61, 49, 61, 56, 14, 13],
       [46, 54, 44, 10, 13,  9, 46, 38,  9, 53]])

In [66]:
arr

array([0, 1, 2, 3, 4, 5])

In [67]:
arr2[0:5]

array([[60, 10, 23, 82,  2, 81, 73, 85, 67, 22],
       [53, 15, 84, 15, 85, 23, 77, 91, 74, 36],
       [75, 29,  7, 99, 93, 19,  3, 72, 72, 80],
       [96, 53, 58, 65, 29,  0, 76, 83, 22, 41],
       [95, 37, 58,  6, 53, 78, 21, 64, 15,  8]])

In [68]:
arr2

array([[60, 10, 23, 82,  2, 81, 73, 85, 67, 22],
       [53, 15, 84, 15, 85, 23, 77, 91, 74, 36],
       [75, 29,  7, 99, 93, 19,  3, 72, 72, 80],
       [96, 53, 58, 65, 29,  0, 76, 83, 22, 41],
       [95, 37, 58,  6, 53, 78, 21, 64, 15,  8],
       [11, 81, 15, 20, 16, 22, 95, 19, 94, 98],
       [17, 30, 14, 15,  8, 33, 78, 71, 33, 27],
       [62, 26, 50, 95, 77, 18, 46, 64, 37, 82],
       [79, 64, 49, 14, 61, 49, 61, 56, 14, 13],
       [46, 54, 44, 10, 13,  9, 46, 38,  9, 53]])

In [69]:
arr2[-5,5]

22

In [70]:
arr2[-5,-5]

22

In [71]:
arr2[::-1] # reverse the matrix

array([[46, 54, 44, 10, 13,  9, 46, 38,  9, 53],
       [79, 64, 49, 14, 61, 49, 61, 56, 14, 13],
       [62, 26, 50, 95, 77, 18, 46, 64, 37, 82],
       [17, 30, 14, 15,  8, 33, 78, 71, 33, 27],
       [11, 81, 15, 20, 16, 22, 95, 19, 94, 98],
       [95, 37, 58,  6, 53, 78, 21, 64, 15,  8],
       [96, 53, 58, 65, 29,  0, 76, 83, 22, 41],
       [75, 29,  7, 99, 93, 19,  3, 72, 72, 80],
       [53, 15, 84, 15, 85, 23, 77, 91, 74, 36],
       [60, 10, 23, 82,  2, 81, 73, 85, 67, 22]])

In [72]:
arr2[::-2]

array([[46, 54, 44, 10, 13,  9, 46, 38,  9, 53],
       [62, 26, 50, 95, 77, 18, 46, 64, 37, 82],
       [11, 81, 15, 20, 16, 22, 95, 19, 94, 98],
       [96, 53, 58, 65, 29,  0, 76, 83, 22, 41],
       [53, 15, 84, 15, 85, 23, 77, 91, 74, 36]])

In [73]:
arr2

array([[60, 10, 23, 82,  2, 81, 73, 85, 67, 22],
       [53, 15, 84, 15, 85, 23, 77, 91, 74, 36],
       [75, 29,  7, 99, 93, 19,  3, 72, 72, 80],
       [96, 53, 58, 65, 29,  0, 76, 83, 22, 41],
       [95, 37, 58,  6, 53, 78, 21, 64, 15,  8],
       [11, 81, 15, 20, 16, 22, 95, 19, 94, 98],
       [17, 30, 14, 15,  8, 33, 78, 71, 33, 27],
       [62, 26, 50, 95, 77, 18, 46, 64, 37, 82],
       [79, 64, 49, 14, 61, 49, 61, 56, 14, 13],
       [46, 54, 44, 10, 13,  9, 46, 38,  9, 53]])

In [74]:
arr2[::-3]

array([[46, 54, 44, 10, 13,  9, 46, 38,  9, 53],
       [17, 30, 14, 15,  8, 33, 78, 71, 33, 27],
       [96, 53, 58, 65, 29,  0, 76, 83, 22, 41],
       [60, 10, 23, 82,  2, 81, 73, 85, 67, 22]])

In [75]:
arr

array([0, 1, 2, 3, 4, 5])

In [76]:
arr.max() 

5

In [77]:
arr.mean()

2.5

In [78]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [79]:
from numpy import *

In [81]:
arr

array([0, 1, 2, 3, 4, 5])

In [83]:
median(arr)

2.5

In [84]:
arr.reshape(2,3)  

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [86]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [90]:
arr3 = np.arange(0,100).reshape(10,10) 

In [91]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [92]:
row = 4
col = 5

In [93]:
arr3[row,col]

45

In [94]:
arr3[4,5]

45

In [95]:
arr3[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [104]:
# With Slices
arr3[:,col] 

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [97]:
arr3[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [98]:
arr3[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [99]:
arr3[:row]  

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [100]:
arr3[row:] 

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [102]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [101]:
arr3[:,8] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [103]:
arr3[:,-1] 

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [105]:
arr3[1,4]

14

In [106]:
arr3[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [107]:
arr3[2:3,4:5]

array([[24]])

In [108]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [109]:
id(arr3)

1629549556720

In [110]:
arr3 < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [111]:
arr3 > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [112]:
arr3 == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [113]:
arr3[arr3==50] 

array([50])

In [115]:
a1 = arr3[arr3<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [116]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [117]:
a2 = arr3[arr3>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [118]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [119]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [120]:
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])