In [3]:
import numpy as np

In [4]:
arr = np.array([[1, 2, 3], # Axis 0 (vertical) → operates column-wise
                [4, 5, 6]]) # Axis 1 (horizontal) → operates row-wise

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.sum(arr, axis=0) # Sum elements

array([5, 7, 9])

In [7]:
np.sum(arr, axis=1) # Sum elements

array([ 6, 15])

In [8]:
np.mean(arr, axis=0) #  # Average of elements

array([2.5, 3.5, 4.5])

In [9]:
np.mean(arr, axis=1) # Average of elements

array([2., 5.])

In [10]:
np.max(arr, axis=0) # Maximum value

array([4, 5, 6])

In [11]:
np.max(arr, axis=1) # Maximum value

array([3, 6])

In [12]:
np.min(arr, axis=0) # Minimum value

array([1, 2, 3])

In [13]:
np.min(arr, axis=1) # Minimum value

array([1, 4])

In [14]:
arr2 = np.array([[3, 4, 1],
                [6, 5, 9]])

In [15]:
arr2

array([[3, 4, 1],
       [6, 5, 9]])

In [16]:
np.sort(arr2, axis=0) # Sort each col

array([[3, 4, 1],
       [6, 5, 9]])

In [17]:
np.sort(arr2, axis=1) # Sort each row

array([[1, 3, 4],
       [5, 6, 9]])

In [18]:
np.delete(arr2, 1, 0) # delete 2nd row 

array([[3, 4, 1]])

In [19]:
np.delete(arr2, 1, 1) # delete 2nd col

array([[3, 1],
       [6, 9]])

In [20]:
arr = np.array([10, 20, 30, 40])

In [21]:
arr

array([10, 20, 30, 40])

In [22]:
np.mean(arr) # Mean

25.0

In [23]:
np.median(arr) # median

25.0

In [24]:
np.std(arr) # Standard deviation 

11.180339887498949

In [25]:
np.max(arr) # Maximum

40

In [26]:
np.min(arr) # Minimum

10

In [27]:
np.sum(arr) # Sum

100

In [28]:
np.flip(arr) # reverse

array([40, 30, 20, 10])