In [29]:
import numpy as np

**Basic Array creation**

In [30]:
arr =  np.array([1,2,3,4,5]) # One Dimensional Array

In [31]:
arr

array([1, 2, 3, 4, 5])

In [32]:
a = [1,2,2.33]

In [33]:
a

[1, 2, 2.33]

In [34]:
np.array(a)

array([1.  , 2.  , 2.33])

In [35]:
l = [[1,2,3],[4,5,6],[7,8,9]]

In [36]:
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [37]:
np.array(l) # # Two Dimensional Array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array Generations finction**

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [40]:
arr = np.zeros(6)

In [41]:
arr

array([0., 0., 0., 0., 0., 0.])

In [42]:
arr = np.zeros((4,5))

In [43]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [45]:
arr = np.ones((4,5))

In [46]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
arr = np.linspace(1,5,2)

In [48]:
arr

array([1., 5.])

In [49]:
arr = np.linspace(0,5,10)

In [50]:
arr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [51]:
arr = np.linspace(0,1,100)

In [52]:
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

**Random Generation fnction**

In [53]:
np.random.rand(10)

array([0.88285736, 0.24834524, 0.60730114, 0.47772634, 0.98997705,
       0.79592951, 0.13435046, 0.60627197, 0.90441302, 0.19339165])

In [54]:
np.random.randn(10)

array([ 1.52795397, -0.10165793, -0.28014496, -0.85728162, -0.90651027,
        0.48520884, -0.27134323, -0.86543367, -2.13333117, -1.70613195])

In [55]:
np.random.randint(10,20,10)

array([17, 11, 17, 10, 16, 18, 17, 13, 10, 11], dtype=int32)

**Array Attributes**

In [58]:
arr = np.array([[1,2,3,4],[5,6,7,8],[2,4,6,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 4, 6, 8]])

In [59]:
arr.shape

(3, 4)

In [60]:
arr.size

12

In [61]:
arr.dtype

dtype('int64')

**Array Method**

In [63]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 4, 6, 8]])

In [65]:
arr.min()

np.int64(1)

In [66]:
arr.max()

np.int64(8)

In [67]:
arr.sum()

np.int64(56)

In [68]:
np.sum(arr, axis=1) # Row

array([10, 26, 20])

In [69]:
np.sum(arr, axis=0) # Column

array([ 8, 12, 16, 20])

In [70]:
arr.mean()

np.float64(4.666666666666667)

In [71]:
arr.std()

np.float64(2.285218200133681)

In [72]:
arr.argmax()

np.int64(7)

In [73]:
arr.argmin()

np.int64(0)

**Reshaping & Resizing**

In [76]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [79]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

**Indexing & Siling Vectors**

In [88]:
arr = np.arange(11,21)

In [89]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [90]:
arr[9] # Indexing

np.int64(20)

In [91]:
arr[1]

np.int64(12)

In [92]:
arr[0:5] # Slicing

array([11, 12, 13, 14, 15])

In [93]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

**Indexing & Siling Matrix**

In [94]:
arr = np.arange(1,31).reshape(6,5)

In [95]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [96]:
arr[3]

array([16, 17, 18, 19, 20])

In [100]:
arr[3,3]

np.int64(19)

In [109]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [112]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [113]:
arr[:,3]

array([ 4,  9, 14, 19, 24, 29])

In [114]:
arr[3,:]

array([16, 17, 18, 19, 20])

**Boolean Indexing**

In [115]:
bool_index = arr %2 == 0

In [116]:
bool_index

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [117]:
arr = arr[bool_index]

In [118]:
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [119]:
arr.shape

(15,)

**Broadcasting**

In [122]:
l =[10,20,30,40]
arr = np.array(l)

In [123]:
arr

array([10, 20, 30, 40])

In [124]:
arr + 10

array([20, 30, 40, 50])

**Deep & Shallow copy**

In [132]:
a= np.arange(1,21) 

In [133]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [134]:
slice = a[:5]

In [135]:
slice * 10

array([10, 20, 30, 40, 50])

In [136]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [137]:
a[4:6] * 10

array([50, 60])

In [139]:
b = a.copy()

In [140]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [141]:
b[0] = 99

In [142]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [143]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**Matrix Operation**

In [148]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [149]:
A

array([[1, 2],
       [3, 4]])

In [150]:
B

array([[5, 6],
       [7, 8]])

In [152]:
A @ B

array([[19, 22],
       [43, 50]])

In [153]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [154]:
A.T

array([[1, 3],
       [2, 4]])

**Stacking Array**

In [156]:
A = np.array([1, 2,3, 4])
B = np.array([5, 6,7, 8])

In [157]:
A

array([1, 2, 3, 4])

In [158]:
B

array([5, 6, 7, 8])

In [160]:
stack = np.vstack((A,B))

In [161]:
stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [162]:
stack2 = np.hstack((A,B))

In [163]:
stack2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [164]:
np.column_stack((A,B))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

**Splitting Array**

In [167]:
a = np.arange(16).reshape(4,4)

In [168]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [174]:
np.hsplit(a,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [176]:
np.vsplit(a,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]